### ISSUE TITLE
Gryff: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by Gryff** [trillian/trillian#11]
Hi there!

I'm a developer with experience in MySQL (advanced procedures and database design), Python and Javascript. 
I've been checking out your project but I'm struggling to find a way to help as there is nothing in the repository. 

Can you suggest something I can help on?

Thanks
Gryff<p><br><blockquote>This issue was created by @Gryff via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by katieannemills** [comment]
Hi @Gryff, welcome aboard!

I'd say the biggest thing we'd like to get off the ground right now is some basics on answering the question, 'how are we going to safely run some arbitrary user code once we receive it?'

Technologies floated so far have been docker, some jiggery-pokery with virtual machines, or linux containers, but not much more clarity than that. In addition to being able to run user code (probably python) in a nicely sandboxed way, we'll also need to be able to mount data external to the sandbox in a read-only fashion within the sandbox. Does this sound like something you'd like to explore?

@demitri, can you offer some more details or guidance too?

**Comment by Gryff** [comment]
Hi @BillMills ,

There's a website I use to improve my coding skills called [Codewars](http://www.codewars.com) which  allows users to execute Python code in a Dockerized Ubuntu 14.04. Their code is [open sourced here on Github](https://github.com/entrefuse/cdr) but looks like it's built on .NET, so not sure how helpful that could be. 
I'm not sure about other things in this sector, but there is [CoreOS](https://coreos.com/) built on top of Docker. From reading through their website the idea is to use Docker for each service and allow them to communicate through etcd. You can also [mount data to be used in the Docker container](https://coreos.com/docs/cluster-management/setup/mounting-storage/), although it's not clear from first read how to make it read-only. 

Does that help at all? I can continue to research into this and the other methods you've mentioned, is this the right place to put my findings or would you prefer some other location?

**Comment by katieannemills** [comment]
Sounds good! Maybe start a new issue to keep your findings in a findable spot - be sure to keep @demitri in the loop, it'll be up to him to decide what to go ahead with. What you point out so far sounds promising; would love to get a demo node set up so we can see what it can really do.

**Comment by demitri** [comment]
Hi Gryff! Thanks very much for your interest. Apologies for the late reply; I was doing a lot of traveling when you signed on. Your skills are exactly what we're looking for. I'm using PostgreSQL for the database, but that's not a huge difference. I'm getting some code together to build the basic framework, and development is coming along. I am creating the first dataset Python object now that will populate the database and given Trillian "pixels"; hopefully once there is one, someone else can follow the template and create more.

The Docker component is another piece that can be started independently, so that would be a great area to explore. I've never used the technology, but it seems like the right choice for what we want to do. If you want to explore how that can be packaged/used, that would be great. It probably doesn't matter too much which Linux distribution is chosen - astronomers tend to use CentOS, but really, I can't think of any reason why to pick one over another.

The way it will work is that someone will write a Python module that does some analysis. It will accept a predefined number of inputs, e.g. a catalog object (a position in the sky plus some number of metadata fields), a spectrum, or an image. It will still need to be defined what this will look like. The Python object will be loaded into a Docker image (plus optionally some supplemental data files) and then sent to the node it is to be run on. The data on that node will be passed to the Python module - the exact mechanism is still to be defined (API? something else?). The data on the node will be considered read/only. I imagine a job queue (Celery+Redis?) running on the node to manage this and collect the results, which will then be returned to the central server.

That's the basic idea - as you can tell there are a lot of specifics to be filled in. Does this sound interesting to work on?

**Comment by Gryff** [comment]
Hi Demitri, it sounds very interesting! 
I'm still a bit fuzzy on the overview, my physics knowledge doesn't go much further than UK A level. I'm going to read your paper on arXiv tonight and then ask you some questions if that's ok? 

I'd like to know @andres-root 's view of how to tackle the Docker implementation, as I saw he has worked with Docker?

**Comment by demitri** [comment]
Thanks! There's a great deal to be done that doesn't require physics knowledge — we're going to be throwing data around from files/database and running arbitrary code on it, which isn't trivial. We're working on breaking down those tasks to be as efficient as we can with the resources we have.

**Comment by Gryff** [comment]
Regarding the breaking down of tasks, I think this project is an ideal candidate for a [Domain-Driven Design](http://en.wikipedia.org/wiki/Domain-driven_design) style of work. We have all the prerequisites for this style: the project is non-trivial, we have OOP experience, domain experts and we can work iteratively. 

Let me know what you think :)

**Comment by demitri** [comment]
Hi @mveritym! It's taken a little time, but we're ready to move things forward and get people plugged into Trillian. If you are still interested, please sign up for the Trillian mailing list (linked below). There is a detailed welcome message with details on where things are now and how to contribute. Hope you can join us!

https://groups.google.com/forum/#!forum/trillianverse

I would definitely like your input on the organizational aspects of a project like this. As I mention in my email, most of the project design is still in my head, and I'm working hard now to transfer it to documentation/organization/code, but particularly to get to a point where I can plug interested people in.

**Comment by demitri** [comment]
Sorry, guilty of some copy/pasting there. I meant to address that to @Gryff. :)

**Comment by trillian** [comment]
Closing outstanding issues.
