### ISSUE TITLE
Ray Sanders: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by ghost** [trillian/trillian#17]
I'm an astronomer, specializing in eclipsing binary stars.  Additionally, I have twenty years of Information Technology experience. I write some code in Python.  While I wouldn't consider myself a strong developer, I would like to assist with this project in any way I can.  Thanks!<p><br><blockquote>This issue was created by @raysanders via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by trillian** [comment]
Hi Ray, thanks for your interest! It would be great to have you join us; apologies for the delay in responding. We're between the design phase and early implementation at the moment. The piece we're working on now is "indexing" individual data sets. For example, I'm writing a script that will read FITS files in a particular archive and calculate (using the header) the polygon that the image covers. This will ultimately be put into a database so that given an ra/dec position, we can answer the question of what data is available at that point. Is this something you'd be interested in helping with? You can also be a very valuable resource in assisting contributors to the project who do have a strong coding background with the astronomy side of things (e.g. using FITS files).

**Comment by ghost** [comment]
Awesome, I'll help where I can. Not the greatest Python dev, but I can't get better at it if I don't work on code.  I'm about to post the start of a python utility to sort out a mess of fits files by filter (UBVRI, JHK, RGB, etc)   It might actually be of interest to your project as well!   In the meantime, I'll gladly help verify data integrity, pipeline testing, etc!

**Comment by demitri** [comment]
Hi @raysanders. Apologies for the late reply again. I've created a new mailing list here to organize efforts and communication, and there is already a detailed "welcome" message.

https://groups.google.com/forum/#!forum/trillianverse

I want to start assigning tasks. I still need to write a lot of documentation to be able to get started on the project. I thought a good approach will be to assign tasks which would then direct me exactly what documentation to write. Hope you can join us!

**Comment by trillian** [comment]
Closing outstanding issues.
